name: golang-lint-test-release
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golang-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

  test:
    needs: lint
    name: tests
    runs-on: ubuntu-latest
    container: golang:1.22.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test
  
  release:
    needs: test
    name: release
    runs-on: ubuntu-latest
    container: docker:26.0.0-dind
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: x7z3/final-main

      - name: Build and push Docker Inage
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}